name: Deploying to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploying...
      - uses: actions/setup-node@master
      - run: npm install
      - run: npm run deploy