name: Deploying to GitHub Pages
on: [push]
jobs:
  build:
    name: Deploying...
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: deploy