name: Deploying to GitHub Pages

runs-on: ubuntu-latest
on: [push]
  branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - run: npm install
      - run: npm run deploy