name: Deploying to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: deploy
